name: Code Quality

on:
    push:
        branches:
            - master
    pull_request: []
    workflow_dispatch:

permissions:
    contents: read
    packages: write
    actions: read

jobs:
  main:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .
